name: learn-gh-actions
on:
  push:
    paths:
      - 'dictionary.txt'
jobs:
  to-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          zip PersonalDictionary.zip dictionary.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add PersonalDictionary.zip
          git commit -m "to zip"
          git push
      - name: discord-notify
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

